Move plugin to its own repository
kaliberjs/sanity-plugin-nav-extend pull request #1
Opened 2024-08-21 08:46 UTC by daveykropf

2024-08-21 12:52 UTC, EECOLOR requested changes

2024-08-21 12:52 UTC, EECOLOR commented on .yarnrc
Waar is deze voor?

2024-08-21 12:52 UTC, EECOLOR commented on scripts/scripts/addPeerDependencies.js
Deze is denk ik niet nodig

2024-08-21 12:52 UTC, EECOLOR commented on .stylelintrc
Deze is denk ik ook niet nodig

2024-08-21 12:52 UTC, EECOLOR commented on .npmignore
Waar is deze voor?

2024-08-23 14:05 UTC, daveykropf commented on .yarnrc
Ik had qua inspiratie voor benodigde bestanden gekeken naar deze PR / repo: https://github.com/kaliberjs/sanity-plugin-duplicate/pull/2

Maar ik zat het bestand verwijderen en kijken of het dan ook zonder problemen werkt.

2024-08-23 14:40 UTC, merged